include(CheckCXXCompilerFlag)
function(AddCompileDefenitions)
    foreach(def IN LISTS ARGN)
	CHECK_CXX_COMPILER_FLAG("${def}"  "FLAG_${def}_available")
	if("${FLAG_${def}_available}")
	    add_definitions("${def}")
	endif( "${FLAG_${def}_available}")
    endforeach(def)
endfunction(AddCompileDefenitions)
